#!/usr/bin/env node

/**
 * Prisma Schema Merge Script
 *
 * This script merges all modular schema files from the models/ directory
 * into a single schema.prisma file for Prisma CLI to use.
 *
 * Usage: node scripts/merge-schema.js
 */

const fs = require('fs');
const path = require('path');

// Configuration
const PRISMA_DIR = path.join(__dirname, '../prisma');
const MODELS_DIR = path.join(PRISMA_DIR, 'models');
const SCHEMA_FILE = path.join(PRISMA_DIR, 'schema.prisma');

// Schema header with datasource and generator configuration
const SCHEMA_HEADER = `// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema
//
// ⚠️  AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// This file is generated by merging modules from models/ directory
// To make changes, edit the individual module files and run: npm run schema:merge

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

// ============================================
// Modular Schema Files
// ============================================
// The following models are imported from individual modules:
`;

/**
 * Get all .prisma files from the models directory
 */
function getModuleFiles() {
  if (!fs.existsSync(MODELS_DIR)) {
    console.error(`Models directory not found: ${MODELS_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(MODELS_DIR)
    .filter(file => file.endsWith('.prisma'))
    .sort(); // Sort alphabetically for consistent ordering

  return files;
}

/**
 * Read and merge all schema modules
 */
function mergeSchemas() {
  console.log('🔄 Merging Prisma schema modules...\n');

  const moduleFiles = getModuleFiles();

  if (moduleFiles.length === 0) {
    console.warn('⚠️  No module files found in models/ directory');
    return;
  }

  console.log(`📦 Found ${moduleFiles.length} module files:`);
  moduleFiles.forEach(file => console.log(`   - ${file}`));
  console.log('');

  // Build the merged schema content
  let mergedContent = SCHEMA_HEADER;

  // Add module file list as comment
  moduleFiles.forEach(file => {
    mergedContent += `// - ${file}\n`;
  });
  mergedContent += '\n';

  // Append each module file's content
  moduleFiles.forEach(file => {
    const filePath = path.join(MODELS_DIR, file);
    const content = fs.readFileSync(filePath, 'utf-8');

    // Add separator comment before each module
    mergedContent += `\n// ============================================\n`;
    mergedContent += `// Module: ${file}\n`;
    mergedContent += `// ============================================\n\n`;
    mergedContent += content;
    mergedContent += '\n';
  });

  // Write the merged schema
  fs.writeFileSync(SCHEMA_FILE, mergedContent, 'utf-8');

  console.log(`✅ Schema merged successfully!`);
  console.log(`📄 Output: ${SCHEMA_FILE}`);
  console.log(`📊 Total modules: ${moduleFiles.length}`);
  console.log('');
}

/**
 * Main execution
 */
try {
  mergeSchemas();
} catch (error) {
  console.error('❌ Error merging schema:', error.message);
  process.exit(1);
}
