import { Application, ApplicationStats, ApplicationStatus } from '@/types/application';

// ============================================
// Mock 数据 - 高质量示例数据（12个完整状态）
// ============================================

export const MOCK_STATS: ApplicationStats = {
  total: 31,
  todayApplied: 5,
  thisWeekApplied: 12,
  thisMonthApplied: 31,
  byStatus: {
    APPLIED: 8,
    HR_INITIAL_CONTACT: 5,
    BUSINESS_SCREENING: 4,
    BUSINESS_FIRST_INTERVIEW: 3,
    BUSINESS_SECOND_INTERVIEW: 2,
    HR_FINAL_INTERVIEW: 2,
    CEO_INTERVIEW: 1,
    OFFER_PENDING: 2,
    PENDING_ONBOARDING: 1,
    HIRED: 1,
    ARCHIVED: 1,
    BLACKLISTED: 1,
  },
};

export const MOCK_APPLICATIONS: Application[] = [
  // 1. 已投递
  {
    id: 'app_001',
    candidateId: 'candidate_001',
    jobId: 'job_001',
    status: 'APPLIED' as ApplicationStatus,
    transparencyLevel: 'STANDARD',
    appliedAt: '2026-03-12T10:30:00Z',
    createdAt: '2026-03-12T10:30:00Z',
    updatedAt: '2026-03-12T10:30:00Z',
    screeningScore: 75,
    matchScore: 82,
    candidate: {
      id: 'candidate_001',
      name: '张伟',
      email: 'zhang.wei@example.com',
      phoneNumber: '+86 138 0013 8888',
      status: 'ACTIVE',
      currentCompany: '腾讯游戏',
      currentTitle: 'Unity 开发工程师',
      location: '深圳',
      yearsOfExperience: 3,
      tags: ['本科', '3年经验', 'Unity'],
    },
    job: {
      id: 'job_001',
      title: 'Unity 高级开发工程师',
      department: '技术部',
      location: '深圳',
      status: 'ACTIVE',
    },
  },
  // 2. HR初步沟通
  {
    id: 'app_002',
    candidateId: 'candidate_002',
    jobId: 'job_001',
    status: 'HR_INITIAL_CONTACT' as ApplicationStatus,
    appliedAt: '2026-03-11T14:20:00Z',
    screeningScore: 80,
    matchScore: 86,
    candidate: {
      id: 'candidate_002',
      name: '李思琪',
      email: 'li.siqi@example.com',
      phoneNumber: '+86 139 1234 5678',
      currentCompany: '网易游戏',
      currentTitle: '游戏客户端开发',
      avatar: undefined,
      location: '广州',
      educationLevel: 'BACHELOR',
      school: '中山大学',
      major: '计算机科学',
      graduationYear: 2020,
      yearsOfExperience: 4,
      status: 'active',
    },
    job: {
      id: 'job_001',
      title: 'Unity 高级开发工程师',
      department: '技术部',
      location: '深圳',
      status: 'ACTIVE',
    },
    tags: ['本科', '4年经验', '中大'],
  },
  // 3. 业务筛选中
  {
    id: 'app_003',
    candidateId: 'candidate_003',
    jobId: 'job_001',
    status: 'BUSINESS_SCREENING' as ApplicationStatus,
    appliedAt: '2026-03-10T09:15:00Z',
    screeningScore: 88,
    matchScore: 90,
    candidate: {
      id: 'candidate_003',
      name: '王芳',
      email: 'wang.fang@example.com',
      phoneNumber: '+86 136 6666 8888',
      currentCompany: '米哈游',
      currentTitle: 'Unity客户端开发',
      avatar: undefined,
      location: '上海',
      educationLevel: 'MASTER',
      school: '上海交通大学',
      major: '软件工程',
      graduationYear: 2019,
      yearsOfExperience: 5,
    },
    job: {
      id: 'job_001',
      title: 'Unity 高级开发工程师',
      department: '技术部',
      location: '深圳',
      status: 'ACTIVE',
    },
    tags: ['硕士', '5年经验', '交大', '米哈游'],
  },
  // 4. 业务初面中
  {
    id: 'app_004',
    candidateId: 'candidate_004',
    jobId: 'job_001',
    status: 'BUSINESS_FIRST_INTERVIEW' as ApplicationStatus,
    appliedAt: '2026-03-09T16:45:00Z',
    screeningScore: 85,
    matchScore: 88,
    candidate: {
      id: 'candidate_004',
      name: '刘强',
      email: 'liu.qiang@example.com',
      phoneNumber: '+86 137 7777 9999',
      currentCompany: '字节跳动',
      currentTitle: '游戏客户端开发',
      avatar: undefined,
      location: '北京',
      educationLevel: 'BACHELOR',
      school: '清华大学',
      major: '计算机科学与技术',
      graduationYear: 2018,
      yearsOfExperience: 6,
    },
    job: {
      id: 'job_001',
      title: 'Unity 高级开发工程师',
      department: '技术部',
      location: '深圳',
      status: 'ACTIVE',
    },
    tags: ['本科', '清华', '6年经验', '字节'],
  },
  // 5. 业务复试中
  {
    id: 'app_005',
    candidateId: 'candidate_005',
    jobId: 'job_001',
    status: 'BUSINESS_SECOND_INTERVIEW' as ApplicationStatus,
    appliedAt: '2026-03-08T11:30:00Z',
    screeningScore: 90,
    matchScore: 92,
    candidate: {
      id: 'candidate_005',
      name: '陈静',
      email: 'chen.jing@example.com',
      phoneNumber: '+86 135 5555 3333',
      currentCompany: '莉莉丝游戏',
      currentTitle: 'Unity高级工程师',
      avatar: undefined,
      location: '上海',
      educationLevel: 'MASTER',
      school: '浙江大学',
      major: '计算机科学',
      graduationYear: 2017,
      yearsOfExperience: 7,
    },
    job: {
      id: 'job_001',
      title: 'Unity 高级开发工程师',
      department: '技术部',
      location: '深圳',
      status: 'ACTIVE',
    },
    tags: ['硕士', '7年经验', '浙大', '莉莉丝'],
  },
  // 6. HR终面
  {
    id: 'app_006',
    candidateId: 'candidate_006',
    jobId: 'job_002',
    status: 'HR_FINAL_INTERVIEW' as ApplicationStatus,
    appliedAt: '2026-03-07T10:00:00Z',
    screeningScore: 92,
    matchScore: 94,
    candidate: {
      id: 'candidate_006',
      name: '赵敏',
      email: 'zhao.min@example.com',
      phoneNumber: '+86 138 8888 6666',
      currentCompany: '叠纸游戏',
      currentTitle: '技术美术',
      avatar: undefined,
      location: '上海',
      educationLevel: 'MASTER',
      school: '中国美术学院',
      major: '艺术设计',
      graduationYear: 2018,
      yearsOfExperience: 6,
    },
    job: {
      id: 'job_002',
      title: '技术美术（TA）',
      department: '美术部',
      location: '上海',
    },
    tags: ['硕士', '6年经验', '美院', 'TA'],
  },
  // 7. CEO面
  {
    id: 'app_007',
    candidateId: 'candidate_007',
    jobId: 'job_001',
    status: 'CEO_INTERVIEW' as ApplicationStatus,
    appliedAt: '2026-03-06T14:30:00Z',
    screeningScore: 95,
    matchScore: 96,
    candidate: {
      id: 'candidate_007',
      name: '孙悟空',
      email: 'sun.wukong@example.com',
      phoneNumber: '+86 139 9999 8888',
      currentCompany: '腾讯游戏',
      currentTitle: 'Unity技术专家',
      avatar: undefined,
      location: '深圳',
      educationLevel: 'PHD',
      school: '斯坦福大学',
      major: '计算机科学',
      graduationYear: 2016,
      yearsOfExperience: 8,
    },
    job: {
      id: 'job_001',
      title: 'Unity 高级开发工程师',
      department: '技术部',
      location: '深圳',
      status: 'ACTIVE',
    },
    tags: ['博士', '8年经验', '斯坦福', '腾讯'],
  },
  // 8. Offer中
  {
    id: 'app_008',
    candidateId: 'candidate_008',
    jobId: 'job_001',
    status: 'OFFER_PENDING' as ApplicationStatus,
    appliedAt: '2026-03-05T09:00:00Z',
    screeningScore: 93,
    matchScore: 95,
    candidate: {
      id: 'candidate_008',
      name: '周瑜',
      email: 'zhou.yu@example.com',
      phoneNumber: '+86 136 7777 5555',
      currentCompany: 'FunPlus',
      currentTitle: 'Unity资深开发',
      avatar: undefined,
      location: '北京',
      educationLevel: 'MASTER',
      school: '北京大学',
      major: '软件工程',
      graduationYear: 2017,
      yearsOfExperience: 7,
    },
    job: {
      id: 'job_001',
      title: 'Unity 高级开发工程师',
      department: '技术部',
      location: '深圳',
      status: 'ACTIVE',
    },
    tags: ['硕士', '7年经验', '北大', 'FunPlus'],
  },
  // 9. 待入职
  {
    id: 'app_009',
    candidateId: 'candidate_009',
    jobId: 'job_003',
    status: 'PENDING_ONBOARDING' as ApplicationStatus,
    appliedAt: '2026-03-01T10:30:00Z',
    screeningScore: 94,
    matchScore: 97,
    candidate: {
      id: 'candidate_009',
      name: '诸葛亮',
      email: 'zhuge.liang@example.com',
      phoneNumber: '+86 135 4444 3333',
      currentCompany: '网易游戏',
      currentTitle: '游戏服务器架构师',
      avatar: undefined,
      location: '杭州',
      educationLevel: 'MASTER',
      school: '清华大学',
      major: '计算机科学',
      graduationYear: 2016,
      yearsOfExperience: 8,
    },
    job: {
      id: 'job_003',
      title: '游戏服务器开发工程师',
      department: '技术部',
      location: '上海',
    },
    tags: ['硕士', '8年经验', '清华', '架构师'],
  },
  // 10. 已入职
  {
    id: 'app_010',
    candidateId: 'candidate_010',
    jobId: 'job_001',
    status: 'HIRED' as ApplicationStatus,
    appliedAt: '2026-02-20T11:00:00Z',
    screeningScore: 96,
    matchScore: 98,
    candidate: {
      id: 'candidate_010',
      name: '韩信',
      email: 'han.xin@example.com',
      phoneNumber: '+86 138 6666 4444',
      currentCompany: '本公司',
      currentTitle: 'Unity高级开发工程师',
      avatar: undefined,
      location: '深圳',
      educationLevel: 'MASTER',
      school: '复旦大学',
      major: '软件工程',
      graduationYear: 2018,
      yearsOfExperience: 6,
    },
    job: {
      id: 'job_001',
      title: 'Unity 高级开发工程师',
      department: '技术部',
      location: '深圳',
      status: 'ACTIVE',
    },
    tags: ['硕士', '6年经验', '复旦', '已入职'],
  },
  // 11. 已归档
  {
    id: 'app_011',
    candidateId: 'candidate_011',
    jobId: 'job_002',
    status: 'ARCHIVED' as ApplicationStatus,
    appliedAt: '2026-02-15T14:00:00Z',
    screeningScore: 70,
    matchScore: 75,
    candidate: {
      id: 'candidate_011',
      name: '杨过',
      email: 'yang.guo@example.com',
      phoneNumber: '+86 137 5555 2222',
      currentCompany: '完美世界',
      currentTitle: '游戏客户端开发',
      avatar: undefined,
      location: '北京',
      educationLevel: 'BACHELOR',
      school: '北京理工大学',
      major: '计算机科学',
      graduationYear: 2019,
      yearsOfExperience: 5,
    },
    job: {
      id: 'job_002',
      title: '技术美术（TA）',
      department: '美术部',
      location: '上海',
    },
    tags: ['本科', '5年经验', '北理', '已归档'],
  },
  // 12. 黑名单
  {
    id: 'app_012',
    candidateId: 'candidate_012',
    jobId: 'job_001',
    status: 'BLACKLISTED' as ApplicationStatus,
    appliedAt: '2026-02-10T10:00:00Z',
    screeningScore: 85,
    matchScore: 88,
    candidate: {
      id: 'candidate_012',
      name: '赵六',
      email: 'zhao.liu@example.com',
      phoneNumber: '+86 138 1234 5678',
      currentCompany: '某竞对公司',
      currentTitle: 'Unity开发',
      avatar: undefined,
      location: '上海',
      educationLevel: 'MASTER',
      school: '同济大学',
      major: '软件工程',
      graduationYear: 2019,
      yearsOfExperience: 5,
    },
    job: {
      id: 'job_001',
      title: 'Unity 高级开发工程师',
      department: '技术部',
      location: '深圳',
      status: 'ACTIVE',
    },
    tags: ['硕士', '5年经验', '黑名单', '竞业限制'],
  },
  // 更多已投递的候选人（用于测试）
  ...Array.from({ length: 7 }, (_, i) => ({
    id: `app_${100 + i}`,
    candidateId: `candidate_${100 + i}`,
    jobId: 'job_001',
    status: 'APPLIED' as ApplicationStatus,
    appliedAt: new Date(Date.now() - i * 86400000).toISOString(),
    screeningScore: 70 + Math.random() * 20,
    matchScore: 75 + Math.random() * 20,
    candidate: {
      id: `candidate_${100 + i}`,
      name: `候选人${i + 1}`,
      email: `candidate${i + 1}@example.com`,
      phoneNumber: `+86 13${Math.floor(Math.random() * 900000000 + 100000000)}`,
      currentCompany: `公司${i + 1}`,
      currentTitle: '游戏开发工程师',
      yearsOfExperience: Math.floor(Math.random() * 8) + 1,
    },
    job: {
      id: 'job_001',
      title: 'Unity 高级开发工程师',
      department: '技术部',
      location: '深圳',
      status: 'ACTIVE',
    },
  })),
];

export const MOCK_CANDIDATES = MOCK_APPLICATIONS.map(app => app.candidate);
export const MOCK_JOBS = [
  { id: 'job_001', title: 'Unity 高级开发工程师' },
  { id: 'job_002', title: '技术美术（TA）' },
  { id: 'job_003', title: '游戏服务器开发工程师' },
];
